# Generated by Django 4.1.7 on 2023-03-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleado',
            table='Empleado',
        ),
    ]
