# Generated by Django 4.1.7 on 2023-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Tecnico',
            },
        ),
    ]
