# Generated by Django 4.1.7 on 2023-03-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_solucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='solucion',
        ),
        migrations.CreateModel(
            name='SolucionRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.repuesto')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solucion')),
            ],
        ),
    ]
