# Generated by Django 4.1.7 on 2023-03-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_remove_repuesto_solucion_solucionrepuesto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solucionrepuesto',
            table='SolucionRepuesto',
        ),
    ]
