# Generated by Django 4.1.7 on 2023-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
